### PR TITLE
Don't pass -D to avahi-daemon

### LINKED ISSUE #29: Avahi - daemon already running
My container logs are spammed with the following message:

> Daemon already running on PID X

The PID inside the container corresponds to the avahi daemon.
It has started after the upgrade from 0.9.2 version of the image (most likely after #28).

I am running the container with "network_mode: host" on Raspberry PI, which already has the avahi daemon running on the host.

#### Environment:

Raspberry Pi 4
Raspbian 10
Docker version 19.03.5, build 633a0ea
Image: mozillaiot/gateway:0.10.0-arm

#### docker-compose.yml:

```
version: "3"

services:
  webthings-gateway:
    container_name: webthings-gateway
    image: mozillaiot/gateway:arm
    restart: unless-stopped
    network_mode: host
    ports:
      - "8080:8080"
      - "4443:4443"
    volumes:
      - ./data:/home/node/.mozilla-iot
```

### PR DESCRIPTION
**Pull request by snorp**
Fixes #29

### CODE REVIEW

**Comment by mrstegeman** [comment]
Unless I'm wrong, I believe avahi-daemon will just keep restarting repeatedly in the background because of the runit service.

**Comment by snorp** [comment]
I think it's trying to restart it constantly right now because of the daemonization. The log spam is from `avahi-daemon` detecting that it's already running and bailing out.

**Comment by mrstegeman** [comment]
`runit` automatically restarts any services in `/etc/service`, as this one is.

https://stackoverflow.com/a/30063607

**Comment by snorp** [comment]
> `runit` automatically restarts any services in `/etc/service`, as this one is.
> 
> https://stackoverflow.com/a/30063607

Right. If you pass `-D` to `avahi-daemon`, it forks and the initial process exits. This means our `run` script exits, and `runit` thinks it needs to try to restart the service. In our case, `avahi-daemon` is still running, and it detects this, generating the log spam.

**Comment by mrstegeman** [comment]
@snorp I see now. I was thinking avahi was crashing.

**Comment by white-gecko** [comment]
Ah cool, I didn't think about that when I added it. Thank you.

**Pull request merged**
